console.log("Date and Time In JS");
let today = new Date();
console.log(today);
console.log(typeof today);
// ==============================================
let otherDate = new Date("09-05-2000 12:40:12");
// otherDate = new Date("june 09 2000");
// otherDate = new Date("05/09/2000");
// console.log(otherDate);
let a;
a = otherDate.getDay();
a = otherDate.getDate();
a = otherDate.getFullYear();
a = otherDate.getHours();
a = otherDate.getMinutes();
a = otherDate.getSeconds();
a = otherDate.getTime();
a = otherDate.getMonth();
console.log(a);
otherDate.setDate(23);
console.log(otherDate);
